function addPolish() {
    translations.pl = {
        'main': 'Zbiór tesuji do shogi',
        'extension': '.kifu',
        'defaultNotation': 'western',
        'return': 'Wróć do menu',
        'choose-notation': 'Wybierz notację:',
        'default-notation': 'domyślna',
        'western-notation': 'zachodnia',
        'japanese-notation': 'japońska',
        'hodges-notation': 'Hodges',
        'hosking-notation': 'Hosking',
        'kitao_kawasaki-notation': 'Kitao-Kawasaki',
        'sasserson-notation': 'Sasserson',
        
        'hu': 'Tesuji dla pionka',
        'hu-1': 'striking pawn (drop)',
        'hu-22': 'dangling pawn',
        'hu-7': 'successive (striking) pawn drops',
        'hu-34': 'pawn drop on the back rank',
        'hu-14': 'sacrifice push',
        'hu-26': 'pawn sacrifice promotion',
        'hu-33': 'counter-push (on another file)',
        'hu-20': 'joining pawns',
        'hu-18': 'opposing pawn (drop)',
        'hu-28': 'dancing pawns',
        'hu-29': 'focal point pawn (drop)',
        'hu-31': 'interposed pawn',
        
        'kyokei': 'Tesuji dla figur lekkich',
        'kyo': 'Tesuji dla lancy',
        'kyo-1': 'lance pin',
        'kyo-2': 'piled-up lances',
        'kyo-3': 'lance in the back ranks',
        'kyo-4': 'advanced lance',
        
        'kei': 'Tesuji dla skoczka',
        'kei-1': 'widełki skoczkiem',
        'kei-3': 'knight in Mino’s yard',
        'kei-4': 'knight (sacrifice) at the head of the pawn',
        'kei-6': 'joining knights',
        'kei-7': 'non-promoted knight',
        'kei-8': 'knight (drop) towards the rear',
        'kei-10': 'counter-jump (not taking the opponent’s knight)',
        
        'ginkin': 'Tesuji dla generałów',
        'gin': 'Tesuji dla srebra',
        'gin-1': 'silver at the head of the knight',
        'gin-2': 'stab-in-the-back',
        'gin-4': 'interposed silver',
        'gin-5': 'silver in king’s belly',
        'gin-7': 'approaching silver',
        
        'kin': 'Tesuji dla złota',
        'kin-1': 'gold at the head (of the king, checkmating)',
        'kin-3': 'send-off gold',
        'kin-5': 'gold (drop) towards the rear',
        'kin-6': 'gold (drop) towards the rear 2',
        'kin-7': 'squeezing gold',
        
        'kakuhi': 'Tesuji dla figur ciężkich',
        'kaku': 'Tesuji dla gońca',
        'kaku-1': 'widełki gońcem',
        'kaku-3': 'goniec zbijający skoczka',
        'kaku-4': 'bishop rapid attack',
        'kaku-5': 'bishop in the own camp',
        'kaku-6': 'bishop approching the king',
        
        'hi': 'Tesuji dla wieży',
        'hi-1': 'widełki wieżą',
        'hi-4': 'rook invasion',
        'hi-5': 'crossroads rook',
        'hi-3': 'rook in the own camp',
        'hi-2': 'advancing rook',
        
        
        'specialMoveNames': {
            "TORYO": "Poddanie się",
            "CHUDAN": "Przerwanie", 
            "SENNICHITE": "Powtórzenie pozycji",
            "TIME_UP": "Koniec czasu",
            "ILLEGAL_MOVE": "Nielegalny ruch",
            "+ILLEGAL_ACTION": "Nielegalny ruch białych",
            "-ILLEGAL_ACTION": "Nielegalny ruch czarnych",
            "JISHOGI": "Impas",
            "KACHI": "Ustalone zwycięstwo",
            "HIKIWAKE": "Ustalony remis",
            "MATTA": "Cofnięcie",
            "TSUMI": "Mat",
            "FUZUMI": "Brak mata",
            "ERROR": "Błąd"
        }
    };
}