function addJapanese() {
    translations.ja = {
        'main': '将棋手筋収集',
        'extension': '.kif',
        'defaultNotation': 'japanese',
        'return': 'メニューに戻る',
        'choose-notation': '表記法の選択',
        'default-notation': 'デフォルト',
        'western-notation': '西洋',
        'japanese-notation': '和風',
        'hodges-notation': 'ホッジス',
        'hosking-notation': 'ホスキング',
        'kitao_kawasaki-notation': '北尾・川崎',
        'sasserson-notation': 'サッセルソン',
        
        'hu': '歩の手筋',
        'hu-1': 'たたきの歩',
        'hu-22': '垂れ歩',
        'hu-7': '連打の歩',
        'hu-34': '底歩',
        'hu-14': '突き捨ての歩',
        'hu-26': '成り捨ての歩',
        'hu-33': '突き違いの歩',
        'hu-20': 'つぎ歩',
        'hu-18': '合わせ歩',
        'hu-28': 'ダンスの歩',
        'hu-29': '焦点の歩',
        'hu-31': '中合の歩',
        
        'kyokei': '香車と桂馬の手筋',
        'kyo': '香車の手筋',
        'kyo-1': '田楽刺し',
        'kyo-2': 'かさね打ち',
        'kyo-3': '下段の香',
        'kyo-4': '先着の香',
        
        'kei': '桂馬の手筋',
        'kei-1': '両取りの桂',
        'kei-3': '美濃くずしの桂',
        'kei-4': '歩頭の桂',
        'kei-6': 'つぎ桂',
        'kei-7': '不成の桂',
        'kei-8': '控えの桂',
        'kei-10': 'はねちがいの桂',
        
        'ginkin': '銀と金の手筋',
        'gin': '銀の手筋',
        'gin-1': '桂頭の銀',
        'gin-2': '割り打ちの銀',
        'gin-4': '銀の中合',
        'gin-5': '腹銀',
        'gin-7': '寄せの銀',
        
        'kin': '金の手筋',
        'kin-1': '頭金',
        'kin-3': 'おくりの金',
        'kin-5': '控えの金',
        'kin-7': 'しばりの金',
        
        'kakuhi': '大駒の手筋',
        'kaku': '角の手筋',
        'kaku-1': '王手飛車',
        'kaku-3': '馬を生け捕る角',
        'kaku-4': '急所の角',
        'kaku-5': '攻防の自陣の角',
        'kaku-6': '寄せの角',
        
        'hi': '飛車の手筋',
        'hi-1': '両取り',
        'hi-4': '打ち込み',
        'hi-5': '十字飛車',
        'hi-3': '自陣飛車',
        'hi-2': '接近飛車',
        
        'specialMoveNames': {},
        '':''
    };
}