function addEnglish() {
    translations.en = {
        'main': 'Shogi Tesuji Collection',
        'extension': '.kif',
        'defaultNotation': 'western',
        'return': 'Return to menu',
        'choose-notation': 'Choose notation:',
        'default-notation': 'Default',
        'western-notation': 'Western',
        'japanese-notation': 'Japanese',
        'hodges-notation': 'Hodges',
        'hosking-notation': 'Hosking',
        'kitao_kawasaki-notation': 'Kitao-Kawasaki',
        'sasserson-notation': 'Sasserson',
        
        'hu': 'Pawn Tesuji',
        'hu-1': 'striking pawn (drop)',
        'hu-22': 'dangling pawn',
        'hu-7': 'successive (striking) pawn drops',
        'hu-34': 'pawn drop on the back rank',
        'hu-14': 'sacrifice push',
        'hu-26': 'pawn sacrifice promotion',
        'hu-33': 'counter-push (on another file)',
        'hu-20': 'joining pawns',
        'hu-18': 'opposing pawn (drop)',
        'hu-28': 'dancing pawns',
        'hu-29': 'focal point pawn (drop)',
        'hu-31': 'interposed pawn',
        
        'kyokei': 'Minor Pieces Tesuji',
        'kyo': 'Lance Tesuji',
        'kyo-1': 'lance pin',
        'kyo-2': 'piled-up lances',
        'kyo-3': 'lance in the back ranks',
        'kyo-4': 'advanced lance',
        
        'kei': 'Knight Tesuji',
        'kei-1': 'knight fork',
        'kei-3': 'knight in Mino’s yard',
        'kei-4': 'knight (sacrifice) at the head of the pawn',
        'kei-6': 'joining knights',
        'kei-7': 'non-promoted knight',
        'kei-8': 'knight (drop) towards the rear',
        'kei-10': 'counter-jump (not taking the opponent’s knight)',
        
        'ginkin': 'General Tesuji',
        'gin': 'Silver Tesuji',
        'gin-1': 'silver at the head of the knight',
        'gin-2': 'stab-in-the-back',
        'gin-4': 'interposed silver',
        'gin-5': 'silver in king’s belly',
        'gin-7': 'approaching silver',
        
        'kin': 'Gold Tesuji',
        'kin-1': 'gold at the head (of the king, checkmating)',
        'kin-3': 'send-off gold',
        'kin-5': 'gold (drop) towards the rear',
        'kin-7': 'squeezing gold',
        
        'kakuhi': 'Major Pieces Tesuji',
        'kaku': 'Bishop Tesuji',
        'kaku-1': 'major bishop fork',
        'kaku-3': 'bishop capturing an horse',
        'kaku-4': 'bishop rapid attack',
        'kaku-5': 'bishop in the own camp',
        'kaku-6': 'bishop approching the king',
        
        'hi': 'Rook Tesuji',
        'hi-1': 'major rook fork',
        'hi-4': 'rook invasion',
        'hi-5': 'crossroads rook',
        'hi-3': 'rook in the own camp',
        'hi-2': 'advancing rook',
        
        'specialMoveNames': {
            "TORYO": "Resignation",
            "CHUDAN": "Interruption", 
            "SENNICHITE": "Repeated position",
            "TIME_UP": "Time up",
            "ILLEGAL_MOVE": "Illegal move",
            "+ILLEGAL_ACTION": "White's illegal move",
            "-ILLEGAL_ACTION": "Black's illegal move",
            "JISHOGI": "Impasse",
            "KACHI": "Adjudicated as victory",
            "HIKIWAKE": "Adjudicated as draw",
            "MATTA": "Undo",
            "TSUMI": "Checkmate",
            "FUZUMI": "No checkmate",
            "ERROR": "Error"
        }
    };
};